import {
  LayoutDashboard, Users2, Briefcase, Package, CalendarCheck, Calculator,
  Receipt, Percent, FileBarChart, Plug, UserCog, Settings, ScrollText,
  Plane, PlaneTakeoff, Bell, Wallet, TrendingUp, ListChecks, FileText, ShieldCheck, CheckSquare, Building2, Activity, Bot,
} from "lucide-react";

// Route -> permission required (mirrors backend). null = any authenticated user.
export const ROUTE_PERMS = {
  "/dashboard": null,
  "/crm": "crm.view",
  "/sales": "sales.view",
  "/sales-activity": "sales.view",
  "/quotations": "quotation.view",
  "/products": ["product.view", "hpp.view"],
  "/booking": "booking.view",
  "/accounting": "accounting.view",
  "/transactions": "transactions.view",
  "/tax": "tax.view",
  "/commission": "commission.view",
  "/approvals": "cancellation.request",
  "/reports": null,
  "/forecast": "super_admin",
  "/n8n": null,
  "/integration": "integration.view",
  "/users": "users.view",
  "/settings": "settings.view",
  "/audit": "audit.view",
  "/packages": "packages.view",
  "/departures": "departures.view",
  "/operations": null,
  "/suppliers": "hpp.view",
  "/hpp": "hpp.view",
  "/notifications": "notifications.view",
  "/follow-ups": "sales.view",
  "/tasks": null,
  "/approval-center": null,
};

export const MENUS = {
  super_admin: [
    { label: "Dashboard", path: "/dashboard", icon: LayoutDashboard },
    { label: "CRM", path: "/crm", icon: Users2 },
    { label: "Sales Management", path: "/sales", icon: Briefcase },
    { label: "Sales Activity", path: "/sales-activity", icon: Activity },
    { label: "Quotations", path: "/quotations", icon: FileText },
    { label: "Follow Ups", path: "/follow-ups", icon: ListChecks },
    { label: "My Tasks", path: "/tasks", icon: CheckSquare },
    { label: "Product Management", path: "/products", icon: Package },
    { label: "Accounting", path: "/accounting", icon: Calculator },
    { label: "Booking", path: "/booking", icon: CalendarCheck },
    { label: "Operations", path: "/operations", icon: PlaneTakeoff },
    { label: "Suppliers", path: "/suppliers", icon: Building2 },
    { label: "Tax", path: "/tax", icon: Receipt },
    { label: "Commission", path: "/commission", icon: Percent },
    { label: "Approval", path: "/approval-center", icon: ShieldCheck },
    { label: "Reports", path: "/reports", icon: FileBarChart },
    { label: "Forecasting", path: "/forecast", icon: TrendingUp },
    { label: "AI Automation", path: "/n8n", icon: Bot },
    { label: "Integration", path: "/integration", icon: Plug },
    { label: "User Management", path: "/users", icon: UserCog },
    { label: "Settings", path: "/settings", icon: Settings },
    { label: "Audit Log", path: "/audit", icon: ScrollText },
  ],
  sales: [
    { label: "My Dashboard", path: "/dashboard", icon: LayoutDashboard },
    { label: "My CRM", path: "/crm", icon: Users2 },
    { label: "My Sales", path: "/sales", icon: Briefcase },
    { label: "My Activity", path: "/sales-activity", icon: Activity },
    { label: "Follow Ups", path: "/follow-ups", icon: ListChecks },
    { label: "My Tasks", path: "/tasks", icon: CheckSquare },
    { label: "Quotations", path: "/quotations", icon: FileText },
    { label: "Bookings", path: "/booking", icon: CalendarCheck },
    { label: "Packages", path: "/packages", icon: Plane },
    { label: "Departures", path: "/departures", icon: PlaneTakeoff },
    { label: "My Commission", path: "/commission", icon: Wallet },
    { label: "Reports", path: "/reports", icon: FileBarChart },
    { label: "Cancellations", path: "/approvals", icon: ShieldCheck },
    { label: "Notifications", path: "/notifications", icon: Bell },
  ],
  accounting: [
    { label: "Accounting Dashboard", path: "/dashboard", icon: LayoutDashboard },
    { label: "Bookings", path: "/booking", icon: CalendarCheck },
    { label: "Invoices & AR", path: "/accounting", icon: Calculator },
    { label: "Operations", path: "/operations", icon: PlaneTakeoff },
    { label: "Suppliers", path: "/suppliers", icon: Building2 },
    { label: "My Tasks", path: "/tasks", icon: CheckSquare },
    { label: "Approval", path: "/approval-center", icon: ShieldCheck },
    { label: "Transactions", path: "/transactions", icon: Receipt },
    { label: "Costing / HPP", path: "/hpp", icon: TrendingUp },
    { label: "Packages", path: "/products", icon: Package },
    { label: "Tax", path: "/tax", icon: Percent },
    { label: "Commission", path: "/commission", icon: Wallet },
    { label: "Reports", path: "/reports", icon: FileBarChart },
    { label: "Notifications", path: "/notifications", icon: Bell },
  ],
};

export const ROLE_LABELS = {
  super_admin: "Super Admin",
  sales: "Sales",
  accounting: "Accounting",
};
