"""Phase 10F-4 — Seed Payments/Invoices/Schedules for 10F-3 bookings.
Consistent: outstanding = total - paid. PAID/PARTIAL/PENDING/OVERDUE. Idempotent (10F4).
Commission is generated by the EXISTING engine (called via API afterwards), NOT hardcoded here.
Does not touch Tax/AI/WhatsApp/SA/Accounting."""
import asyncio
from datetime import datetime, timezone
from bson import ObjectId
from motor.motor_asyncio import AsyncIOMotorClient

ENV = {}
with open("/app/backend/.env") as fh:
    for ln in fh:
        ln = ln.strip()
        if ln and not ln.startswith("#") and "=" in ln:
            k, v = ln.split("=", 1); ENV[k] = v.strip().strip('"')
db = AsyncIOMotorClient(ENV["MONGO_URL"])[ENV["DB_NAME"]]
NOW = datetime.now(timezone.utc).isoformat()
TODAY = NOW[:10]

async def nn(prefix, coll, field):
    n = await coll.count_documents({}) + 1
    while await coll.find_one({field: f"{prefix}-{n:05d}"}):
        n += 1
    return f"{prefix}-{n:05d}"

# scenario plan across bookings (index order): PAID/PARTIAL/PENDING/OVERDUE
PLAN = (["PAID"] * 9 + ["PARTIAL"] * 8 + ["PENDING"] * 4 + ["OVERDUE"] * 3)

async def main():
    if await db.demo_seed_flags.find_one({"batch": "10F4"}):
        print("Already seeded (10F4). Skipping."); return
    bookings = await db.bookings.find({"seed_batch": "10F3"}).sort("created_at", 1).to_list(500)
    if not bookings:
        print("ERROR: no 10F3 bookings"); return
    tot_all = paid_all = out_all = 0.0
    dist = {}
    for i, b in enumerate(bookings):
        if b.get("status") == "CANCELLED":
            continue
        bid = str(b["_id"])
        total = round(float(b.get("total") or 0), 2)
        scen = PLAN[i % len(PLAN)]
        dp = round(total * 0.4)
        if scen == "PAID":
            paid = total; due = TODAY
        elif scen == "PARTIAL":
            paid = dp; due = TODAY
        elif scen == "OVERDUE":
            paid = 0.0; due = "2026-07-01"
        else:  # PENDING
            paid = 0.0; due = TODAY
        outstanding = round(total - paid, 2)

        # Invoice
        inv_no = await nn("INV", db.invoices, "invoice_number")
        inv = {"invoice_number": inv_no, "booking_id": bid, "booking_number": b.get("booking_number"),
               "customer_id": b.get("customer_id"), "customer_name": b.get("customer_name"),
               "package_id": b.get("package_id"), "package_name": b.get("package_name"),
               "pax": b.get("pax"), "per_pax_price": b.get("per_pax_price"),
               "amount": b.get("subtotal"), "subtotal": b.get("subtotal"),
               "discount_amount": b.get("discount_amount", 0), "discount_percent": b.get("discount_percent", 0),
               "tax_percent": 0, "tax_amount": 0, "total": total,
               "paid_amount": paid, "outstanding": outstanding, "due_date": due,
               "sales_pic_id": b.get("sales_pic_id"), "sales_pic_name": b.get("sales_pic_name"),
               "branch": b.get("branch", ""), "created_at": NOW, "created_by": "System (10F4)", "seed_batch": "10F4"}
        # status per _recompute_invoice_status logic
        if paid >= total and total > 0:
            inv["status"] = "Paid"
        elif paid > 0:
            inv["status"] = "Partially Paid"
        else:
            inv["status"] = "Unpaid"
        if inv["status"] in ("Unpaid", "Partially Paid") and due < TODAY:
            inv["status"] = "Overdue"
        ires = await db.invoices.insert_one(inv)
        iid = str(ires.inserted_id)

        # Payment record(s)
        if paid > 0:
            pay_no = await nn("PAY", db.payments, "reference_number")
            await db.payments.insert_one({"invoice_id": iid, "invoice_number": inv_no, "booking_id": bid,
                "booking_number": b.get("booking_number"), "customer_id": b.get("customer_id"),
                "customer_name": b.get("customer_name"), "amount": paid, "payment_date": "2026-08-10",
                "method": "TRANSFER", "reference_number": pay_no, "status": "CONFIRMED",
                "created_at": NOW, "created_by": "System (10F4)", "seed_batch": "10F4"})

        # Booking payment_schedule (DP + Pelunasan)
        sched = [
            {"payment_number": 1, "label": "DP", "due_date": due, "amount": dp,
             "paid_amount": min(paid, dp), "outstanding": max(dp - min(paid, dp), 0),
             "status": "PAID" if paid >= dp else ("PARTIAL" if paid > 0 else "UNPAID")},
            {"payment_number": 2, "label": "Pelunasan", "due_date": "2026-10-01",
             "amount": round(total - dp, 2), "paid_amount": max(paid - dp, 0),
             "outstanding": max(round(total - dp, 2) - max(paid - dp, 0), 0),
             "status": "PAID" if paid >= total else ("PARTIAL" if paid > dp else "UNPAID")},
        ]
        upd = {"payment_schedule": sched, "payment_plan": "DP", "paid_total": paid,
               "outstanding_total": outstanding, "invoice_id": iid, "invoice_number": inv_no,
               "payment_status": {"PAID": "PAID", "PARTIAL": "PARTIAL", "PENDING": "PENDING", "OVERDUE": "OVERDUE"}[scen]}
        if scen == "PAID":
            upd["status"] = "PAID"; upd["full_payment_date"] = "2026-08-10"
            upd["commission_eligible"] = True; upd["commission_eligible_date"] = "2026-08-10"
        elif scen == "PARTIAL":
            if b.get("status") in ("CONFIRMED", "PENDING"):
                upd["status"] = "PARTIAL_PAID"
        await db.bookings.update_one({"_id": b["_id"]}, {"$set": upd})

        tot_all += total; paid_all += paid; out_all += outstanding
        dist[scen] = dist.get(scen, 0) + 1

    await db.demo_seed_flags.insert_one({"batch": "10F4", "created_at": NOW})
    print(f"SEED DONE | bookings={sum(dist.values())} dist={dist}")
    print(f"TOTAL={round(tot_all)} PAID={round(paid_all)} OUTSTANDING={round(out_all)}")

asyncio.run(main())
